Packaging v2
haotian-liu/yolact_edge pull request #120
Opened 2021-05-14 17:33 UTC by simutisernestas

hey, i've updated the packaging format as you suggested. Evaluation and training scripts are left in the root directory while the package itlsef is moved to the yolact_edge directory. This way we can keep all functionality of those nice scripts and have portable package for folks to use it in scripts. Also these changes are on the laters master branch. I guess the old branch of packaging can go and we could create new one for this PR or merge it to master if you're happy with the result. Thanks!

2021-05-21 16:43 UTC, haotian-liu commented
Thank you so much on your work in packaging, I will be looking into this soon.

2021-05-27 20:27 UTC, SteveMacenski commented
@haotian-liu I also took a look over this - I'm happy with these changes and I think they should be merged :-)

2021-05-28 00:08 UTC, haotian-liu requested changes
Thank you so much for your implementation. They look great! There are a few concerns I have which I left as comments (you could share your thoughts over the comments). Furthermore, I believe `./docker/`, `data/scripts/`, `data/*.gif` should be moved to the root directory.

One major concern I have is about the `config.py`. I am still unsure about how we should deal with this (as this might be a internal issue of the original design). Ideally, the specific configs should be in the root directory (say under `./data/config.py`), while how `cfg` are initialized should be in the `package_root/data/config.py`. Maybe one way of doing is to implement a copy function, where we have a default cfg in `package_root/data/config.py` served as the global. And we can replace that with any config objects we later have. What's your opinion towards this?

Some other files in `./scripts` might also need to be moved but for which file speficially in `scripts` folder should be moved, we can discuss later.

Thank you so much again for contributing to our code base.

2021-05-28 00:10 UTC, haotian-liu commented
@SteveMacenski Thank you for also reviewing this. The contribution looks good, while I have some concerns over a part of it. I left the comments in the review above, and it will be really appreciated if you would like to share your thoughts too. Thanks.

2021-05-30 15:21 UTC, simutisernestas commented on test.py
> +
no idea how i've missed it 😄

2021-05-30 15:25 UTC, simutisernestas commented on yolact_edge/layers/functions/detection.py
> +            preds = torch.cat([boxes[conf_mask], cls_scores[:, None]], dim=1).detach().cpu().numpy()
when doing inference Pytorch is complaining about it and says that you should detach the vector before moving it to CPU (can't recall the actual error, but it's something along those lines). Do you know how to solve that in another way?

2021-06-01 18:33 UTC, simutisernestas commented on .gitignore
> +calib_images
done

2021-06-01 18:36 UTC, simutisernestas commented on yolact_edge/layers/functions/detection.py
> +            preds = torch.cat([boxes[conf_mask], cls_scores[:, None]], dim=1).detach().cpu().numpy()
I've removed this one at the moment. Would be nice to hear your comment on this issue anyways. I'm still wondering why I encountered this error.

2021-06-01 18:36 UTC, simutisernestas commented on README.md
> +calib_images = "/home/ernestas/test/calib_images"
done

2021-06-01 18:38 UTC, simutisernestas commented on README.md
> +import time
i've created ```pkg_usage.py```, couldn't think of a better name 😄

2021-06-01 18:38 UTC, simutisernestas commented on README.md
> +config = model_configs[-5]
i was counting from the other end of the list 😅  fixed this too

2021-06-01 18:39 UTC, simutisernestas commented on test.py
> +
deleted

2021-06-01 18:43 UTC, haotian-liu commented on yolact_edge/layers/functions/detection.py
> +            preds = torch.cat([boxes[conf_mask], cls_scores[:, None]], dim=1).detach().cpu().numpy()
It was most probably due to that you did not use `with torch.no_grad()` and the returned tensors are some part of the computational graph (with gradients)?

2021-06-01 18:47 UTC, haotian-liu commented
Not sure if you have finished updating the PR, but there were some comments that I could not add in the files. Thanks!

> Furthermore, I believe ./docker/, data/scripts/, data/*.gif should be moved to the root directory.
> 
> One major concern I have is about the config.py. I am still unsure about how we should deal with this (as this might be a internal issue of the original design). Ideally, the specific configs should be in the root directory (say under ./data/config.py), while how cfg are initialized should be in the package_root/data/config.py. Maybe one way of doing is to implement a copy function, where we have a default cfg in package_root/data/config.py served as the global. And we can replace that with any config objects we later have. What's your opinion towards this?
> 
> Some other files in ./scripts might also need to be moved but for which file speficially in scripts folder should be moved, we can discuss later.

2021-06-02 06:38 UTC, simutisernestas commented on yolact_edge/layers/functions/detection.py
> +            preds = torch.cat([boxes[conf_mask], cls_scores[:, None]], dim=1).detach().cpu().numpy()
indeed, that's the case. Thanks!

2021-06-02 06:39 UTC, simutisernestas commented
Yeah, i've missed those. I'll get back to the comment soon.

2021-06-02 17:29 UTC, simutisernestas commented
The original implementation of config.py is quite nasty, any time i've touched it while playing with code everything starts breaking. As I understand under the current situation everthing would work fine and the configuration contained in that file only specifies static parameters for different weights and datasets. What would be the benefits of moving it to root directory? 

IMHO ideal case would be to have a proper config file (for instance `YAML` format) which would be required as input alongside the model weights and expose only dynamic parameters which should be modified by the user. However, it would require quite some effort i guess.

I still have to take a second look at this later to make reasonable assessment.

2021-06-19 03:24 UTC, haotian-liu approved these changes

2021-06-19 04:16 UTC, SteveMacenski commented
Awesome! This will make releasing binaries of this _much_ easier in the ROS ecosystem so we can leverage it in the navigation system dynamic obstacle integrations! Once we have some demos / things merged in, we'll follow up to show you how your work is making a real impact in mobile robotics world wide once the integration is complete!

2021-06-19 04:17 UTC, merged

2021-06-19 04:18 UTC, haotian-liu commented
Merged. Thank you so much in supporting our work!
@simutisernestas @SteveMacenski

2021-06-19 04:23 UTC, SteveMacenski commented
Thank @simutisernestas, I'm just an observer / motivator :1st_place_medal: